### ISSUE TITLE
Week 3, exercise 4

### ISSUE THREAD

**Issue by natashabeckerb** [CHCAA-EDUX/scientific-computing-01#18]
Hi, I have a problem with exercise 4: "Create a file called functions.py. In it, write a function character_count that takes a string and counts the number of characters. Create another file, main.py. From main.py, import character_count and apply it to a string."

This is my code: 
``` {r}
def character_count(txt):
	result = 0
	for char in txt:
		result += 1   
	return result

print(character_count("hej")
```

The issue is that the function also counts spaces as characters. How should I change my code to avoid it?

**Comment by martbern** [comment]
Hi Natascha! 

Sorry about the late reply.

Many ways to do this! A simple, readable way to do this is checking if a character is a space using an `if` statement, like 
```python
if char != " ":
    result += 1
```

**Comment by KennethEnevoldsen** [comment]
I assume this question is solved, @natashabeckerb? I will close it for now but reopen it if there is still problems.

**Comment by natashabeckerb** [comment]
Yes thank you!
